# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fece6afc8802df945310589ee36242c48bd454b6af3a9065cb4ded33221fff3871696d14a7e94d605a7d4de2d17808961d31c3156c59263dbf8ecc5fddcea52

test:
  secret_key_base: a0019fbf636810fc094562d0b5ba1ce8cea6911d29db831bef8b92d27281ba1e6c92a6d8ecabdb214fffaca231650464804c75b5afaa8c524c14b6ba00ccbffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
